{
  "stats": {
    "suites": 0,
    "tests": 1,
    "passes": 0,
    "pending": 0,
    "failures": 1,
    "start": "2022-11-07T02:28:40.820Z",
    "end": "2022-11-07T02:28:41.217Z",
    "duration": 397,
    "testsRegistered": 1,
    "passPercent": 0,
    "pendingPercent": 0,
    "other": 0,
    "hasOther": false,
    "skipped": 0,
    "hasSkipped": false
  },
  "results": [
    {
      "uuid": "c82b38e4-9418-4b0a-b39c-acfbfd70c571",
      "title": "",
      "fullFile": "cypress/e2e/newflow.cy.js",
      "file": "cypress/e2e/newflow.cy.js",
      "beforeHooks": [],
      "afterHooks": [],
      "tests": [
        {
          "title": "An uncaught error was detected outside of a test",
          "fullTitle": "An uncaught error was detected outside of a test",
          "timedOut": null,
          "duration": 340,
          "state": "failed",
          "speed": null,
          "pass": false,
          "fail": true,
          "pending": false,
          "context": null,
          "code": "throw err;",
          "err": {
            "message": "CypressError: The following error originated from your test code, not from Cypress.\n\n  > Cannot call `cy.visit()` outside a running test.\n\nThis usually happens when you accidentally write commands outside an `it(...)` test.\n\nIf that is the case, just move these commands inside an `it(...)` test.\n\nCheck your test file for errors.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n\nhttps://on.cypress.io/cannot-execute-commands-outside-test",
            "estack": "CypressError: The following error originated from your test code, not from Cypress.\n\n  > Cannot call `cy.visit()` outside a running test.\n\nThis usually happens when you accidentally write commands outside an `it(...)` test.\n\nIf that is the case, just move these commands inside an `it(...)` test.\n\nCheck your test file for errors.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n\nhttps://on.cypress.io/cannot-execute-commands-outside-test\n    at $Cy.ensureRunnable (http://localhost:53937/__cypress/runner/cypress_runner.js:147516:76)\n    at cy.<computed> [as visit] (http://localhost:53937/__cypress/runner/cypress_runner.js:157545:10)\n    at Object.create (http://localhost:53937/__cypress/runner/cypress_runner.js:103460:19)\n    at context.describe.context.context (http://localhost:53937/__cypress/runner/cypress_runner.js:103236:27)\n    at createRunnable (http://localhost:53937/__cypress/runner/cypress_runner.js:162465:31)\n    at <unknown> (http://localhost:53937/__cypress/runner/cypress_runner.js:162533:14)\n    at <unknown> (http://localhost:53937/__cypress/runner/cypress_runner.js:165590:23)\n    at tryCatcher (http://localhost:53937/__cypress/runner/cypress_runner.js:11318:23)\n    at Object.gotValue (http://localhost:53937/__cypress/runner/cypress_runner.js:10460:18)\n    at Object.gotAccum (http://localhost:53937/__cypress/runner/cypress_runner.js:10449:25)\n    at Object.tryCatcher (http://localhost:53937/__cypress/runner/cypress_runner.js:11318:23)\n    at Promise._settlePromiseFromHandler (http://localhost:53937/__cypress/runner/cypress_runner.js:9253:31)\n    at Promise._settlePromise (http://localhost:53937/__cypress/runner/cypress_runner.js:9310:18)\n    at Promise._settlePromise0 (http://localhost:53937/__cypress/runner/cypress_runner.js:9355:10)\n    at Promise._settlePromises (http://localhost:53937/__cypress/runner/cypress_runner.js:9435:18)\n    at _drainQueueStep (http://localhost:53937/__cypress/runner/cypress_runner.js:6025:12)\n    at _drainQueue (http://localhost:53937/__cypress/runner/cypress_runner.js:6018:9)\n    at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:53937/__cypress/runner/cypress_runner.js:6034:5)\n    at Async.drainQueues (http://localhost:53937/__cypress/runner/cypress_runner.js:5904:14)",
            "diff": null
          },
          "uuid": "277ef29a-546a-4a78-baa9-628b5687eb40",
          "parentUUID": "c82b38e4-9418-4b0a-b39c-acfbfd70c571",
          "isHook": false,
          "skipped": false
        }
      ],
      "suites": [],
      "passes": [],
      "failures": [
        "277ef29a-546a-4a78-baa9-628b5687eb40"
      ],
      "pending": [],
      "skipped": [],
      "duration": 340,
      "root": true,
      "rootEmpty": false,
      "_timeout": 2000
    }
  ],
  "meta": {
    "mocha": {
      "version": "7.0.1"
    },
    "mochawesome": {
      "options": {
        "quiet": false,
        "reportFilename": "mochawesome",
        "saveHtml": true,
        "saveJson": true,
        "consoleReporter": "spec",
        "useInlineDiffs": false,
        "code": true
      },
      "version": "7.1.3"
    },
    "marge": {
      "options": null,
      "version": "6.2.0"
    }
  }
}